def ft_draw_display(attempts):
    if attempts == 6:
        print(" _____")
        print("|     |")
        print("|")
        print("|")
        print("|")
        print("|")
        print("\nThe gallows was built. Get ready to be hung!")
    elif attempts == 5:
        print(" _____")
        print("|     |")
        print("|     O")
        print("|")
        print("|")
        print("|")
    elif attempts == 4:
        print(" _____")
        print("|     |")
        print("|     O")
        print("|     |")
        print("|")
        print("|")
    elif attempts == 3:
        print(" _____")
        print("|     |")
        print("|     O")
        print("|    /|")
        print("|")
        print("|")
    elif attempts == 2:
        print(" _____")
        print("|     |")
        print("|     O")
        print("|    /|\\")
        print("|")
        print("|")
    elif attempts == 1:
        print(" _____")
        print("|     |")
        print("|     O")
        print("|    /|\\")
        print("|    / \\")
        print("|")
    elif attempts == 0:
        print(" _____")
        print("|     |")
        print("|     O")
        print("|        ")
        print("|    /|\\")
        print("|    / \\")
        print("The neck couldn't support the weight of the body...")